trigger:
  batch: true
  branches:
    include:
      - master
      - release/*

variables:
  - group: ContainerAppsDemo-test

stages:
  - stage: Build
    displayName: Build & Push
    jobs:
      - template: ../jobs/build-push.yml
        parameters:
          jobName: BuildOrders
          dockerfilePath: src/OrdersApi/Dockerfile
          imageRepository: ordersapi
          acrLoginServer: $(ACR_LOGIN_SERVER)
          acrServiceConnection: $(ACR_SERVICE_CONNECTION)

      - template: ../jobs/build-push.yml
        parameters:
          jobName: BuildPayments
          dockerfilePath: src/PaymentsApi/Dockerfile
          imageRepository: paymentsapi
          acrLoginServer: $(ACR_LOGIN_SERVER)
          acrServiceConnection: $(ACR_SERVICE_CONNECTION)

  - stage: DeployOrders
    displayName: Deploy Orders API
    dependsOn: Build
    jobs:
      - template: ../jobs/deploy.yml
        parameters:
          environment: test
          containerAppName: $(ORDERS_API_APP_NAME)
          resourceGroup: $(RESOURCE_GROUP)
          acrLoginServer: $(ACR_LOGIN_SERVER)
          imageRepository: ordersapi
          azureServiceConnection: $(AZURE_SERVICE_CONNECTION)

  - stage: DeployPayments
    displayName: Deploy Payments API
    dependsOn: Build
    jobs:
      - template: ../jobs/deploy.yml
        parameters:
          environment: test
          containerAppName: $(PAYMENTS_API_APP_NAME)
          resourceGroup: $(RESOURCE_GROUP)
          acrLoginServer: $(ACR_LOGIN_SERVER)
          imageRepository: paymentsapi
          azureServiceConnection: $(AZURE_SERVICE_CONNECTION)
